version: "3"
services:
        postgres:
                image: postgres:11-alpine
                restart: always
                volumes:
                        - ${PWD}/data:/var/lib/postgresql/data
                environment:
                        POSTGRES_USER: featmap
                        POSTGRES_DB: featmap
                        POSTGRES_PASSWORD: password
        featmap:
                image: amborle/featmap:v${FEATMAP_VERSION}
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile
                        args:
                                - featmap_version=${FEATMAP_VERSION}
                depends_on: 
                        - postgres
                ports:
                        - 8086:80
                volumes:
                        - ${PWD}/config/conf.json:/opt/featmap/conf.json

