on: push
name: CI
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run custom command
        uses: cedrickring/golang-action@1.4.1
        with:
          args: go test ./...